- hosts: all
 # 使用sudo權限執行指令
  become: true

  vars:
    # 參數
    hostname: mywordpress 

  tasks:
    # "name 參數會顯示在畫面上"
    - name: ==> 0 - add host info 
      # @see <a href="http://docs.ansible.com/ansible/lineinfile_module.html">lineinfile spec</a>
      # @see <a href="http://docs.ansible.com/ansible/playbooks_filters.html">Jinja2 filter</a>
      lineinfile: dest=/etc/hosts line="10.0.0.10  {{ hostname }}" state=present

