- hosts: all
  become: true

  vars:
    hostname: mywordpress

  tasks:
    - name: ==> 0 - add host info # "name 參數會顯示在畫面上"
      lineinfile: dest=/etc/hosts line="10.0.0.10  {{ hostname }}" state=present
      # @see <a href="http://docs.ansible.com/ansible/lineinfile_module.html">lineinfile spec</a>

